behaviors:
  MoveToGoal:

    trainer_type: ppo

    hyperparameters:
      batch_size: 64
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: False
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
          deterministic: False

    max_steps: 1000000
    time_horizon: 1024
    summary_freq: 10000

#    behavioral_cloning:
#      demo_path: demo/MoveToGoal.demo
#      strength: 0.5
#      steps: 150000
#      batch_size: 512
#      num_epoch: 3
#      samples_per_update: 0