behaviors:
  MoveToGoal:

    trainer_type: ppo

    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
          deterministic: false

    max_steps: 1000000
    time_horizon: 1024
    summary_freq: 10000
