behaviors:
  MoveToGoal:

    trainer_type: ppo

    hyperparameters:
      batch_size: 32
      buffer_size: 512
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000

#    behavioral_cloning:
#      demo_path: demo/MoveToGoal.demo
#      strength: 0.5
#      steps: 150000
#      batch_size: 512
#      num_epoch: 3
#      samples_per_update: 0